### ISSUE TITLE
Ownership/Maintenance

### ISSUE THREAD

**Issue by Callek** [remkade/matchspec#32]
@remkade - Do you want to continue to own this, or should I or someone else at Anaconda take over?

I've already made a small adjustment to make this buildable with less configuration on OSX. (and dubbed it as 2.2) but I don't have access to upload to `pypi` of course.

https://pypistats.org/packages/rust-matchspec  Suggests that there are at least *some* users of the python package, but not certain.

We have at least forked this into our github org.

**Comment by remkade** [comment]
I would suggest probably just working off of your github. If you need access to the pypi package I can probably hand that off.

**Comment by Callek** [comment]
> I would suggest probably just working off of your github. If you need access to the pypi package I can probably hand that off.

I don't need access to pypi, was just seeing that it existed there and wondered if it made sense to take it over too.

I'm not certain if anyone uses the pypi version or not

**Comment by remkade** [comment]
Ok great. Let me know if you need anything else!
